export default strings = {
    sign_in: "Sign in",   
    email: "Email",
    password: "Password",
    new_here: "New here?  ",
    register: "Register",
    name: "Name",
    feed: "Feed",
    create_post: "+ Create Post",
    no_data: "No Data Found!",
    no_post: "New Post",
    cancel: "Cancel",
    title: "Title",
    description: "Description",
    price: "Price (USD)",
    upload_photo: "Upload Photo",
    public: "Public",
    private: "Private",
    btn_create_post: "Create Post",
    comment: "Comment",
    home: "Home",
    no_title: "No Title",
    write_your_message: "Write your comment here",
    already_have_an_account: "Already have an account?  ",
    password_validation: "at least 6 characters long",
    error_text_name: "Please enter name",
    error_text_email: "Please enter valid email address",
    error_text_password: "Password must be atleast 6 characters long",
    call_fail_error: "Unable to process request at the moment, try again later",
    enter_valid_data: "All fields are compulsory"
}