
export const SIGN_UP_WITH_EMAIL = 'SIGN_UP_WITH_EMAIL'
export const SIGN_UP_WITH_EMAIL_SUCCESS = 'SIGN_UP_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL_ERROR = 'SIGN_UP_WITH_EMAIL_ERROR';

export const SIGN_IN_WITH_EMAIL = 'SIGN_IN_WITH_EMAIL'
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_ERROR = 'SIGN_IN_WITH_EMAIL_ERROR';

export const FETCH_ALL_POSTS_LIST = 'FETCH_ALL_POSTS_LIST'
export const FETCH_ALL_POSTS_LIST_ERROR = 'FETCH_ALL_POSTS_LIST_ERROR'
export const FETCH_ALL_POSTS_LIST_SUCCESS = 'FETCH_ALL_POSTS_LIST_SUCCESS'

export const CREATE_FEED_POST = 'CREATE_FEED_POST'
export const CREATE_FEED_POST_ERROR = 'CREATE_FEED_POST_ERROR'
export const CREATE_FEED_POST_SUCCESS = 'CREATE_FEED_POST_SUCCESS'